import com.ionspin.kotlin.bignum.decimal.BigDecimal

data class TaxMonthInfo(
    val month: Month,
    val workdays: Int,
    val sickDays: Int,
    val contractIncome: BigDecimal,
    val bonusesIncome: BigDecimal,
    val grossIncome: BigDecimal,
    val ppkTax: BigDecimal,
    val nettDeductions: BigDecimal,
    val foodVouchersTotal: BigDecimal,
    val foodVouchersTaxable: BigDecimal,
    val foodVouchersCompensation: BigDecimal,
    val yearlyZusBase: BigDecimal,
    val zusBase: BigDecimal,
    val retirementTax: BigDecimal,
    val disabilityTax: BigDecimal,
    val sicknessTax: BigDecimal,
    val healthTax: BigDecimal,
    val zus: BigDecimal,
    val yearlyPitBase: BigDecimal,
    val pitBase: BigDecimal,
    val normalPIT: BigDecimal,
    val increasedPIT: BigDecimal,
    val pitTaxFree: BigDecimal,
    val pitHealthReduce: BigDecimal,
    val pit: BigDecimal,
    val nettIncome: BigDecimal,
    val log: List<String>,
)